server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.128.134:3306/cms?useunicode=true;&characterEncoding=utf8
    data-username: root
    data-password: root
